### ISSUE TITLE
这个游戏第一关怎么就卡了

### ISSUE THREAD

**Issue by luogewhu** [buger404/Moristory2#1]
走到你们图标点，有个美女弹框"。。。"然后就没有了，后面点啥游戏界面都不变了

**Comment by buger404** [comment]
你好，请留意游戏开头的过场提示噢，这是个早期预览开发版本（alpha），大部分功能没有完善，游戏基本无法进行

**Comment by buger404** [comment]
目前还在基础功能测试阶段，感谢你对该项目的关心，请期待后续更新哦~
有可以正常玩耍的版本后我会在release里创建一个新的tag（目前release里没有可以玩的）

**Comment by buger404** [comment]
如有其他问题请reopen噢~
